server:
  port: 8080

spring:
  application:
    name: demo-boot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/misc?characterEncoding=utf8&useSSL=true&verifyServerCertificate=false&serverTimezone=Asia/Shanghai&tinyInt1isBit=false&allowMultiQueries=true
    username: root
    password: root
    initial-size: 30
    max-active: 100
    max-wait: 60000
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    mode: LEGACYHTML5
# mybatis mapper
mybatis:
  type-aliases-package: com.demo.boot.core.dao.entity
  mapper-locations: classpath*:mapper/*.xml
  config-location: classpath:/mybatis-config.xml

# log
logging:
  level:
    com.demo.boot.core.dao.mapper: debug
    org.springframework: info
